---

- name: Install epel release
  yum:
    name: epel-release

- name: Yum update all
  yum:
    name: '*'
    state: latest
    exclude: kernel*

- name: "Config sshd"
  lineinfile:
    path: "/etc/ssh/sshd_config"
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - {regexp: '^\s*ClientAliveInterval\s+', line: 'ClientAliveInterval 120'}
    - {regexp: '^\s*ClientAliveCountMax\s+', line: 'ClientAliveCountMax 720'}
    - {regexp: '^\s*GSSAPIAuthentication\s+', line: 'GSSAPIAuthentication no'}
    - {regexp: '^\s*UseDNS\s+', line: 'UseDNS no'}

- name: "Restart sshd"
  systemd:
    state: restarted
    daemon_reload: yes
    name: sshd

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"
  when: reset_hostname | bool

- name: change user passwd
  user: name={{ item.name }} password={{ item.chpass | password_hash('sha512', 'mysecretsalt') }}
  with_items:
       - { name: 'root', chpass: '{{ rootpass }}' }
  when: reset_root_password | bool

- name: Install common packages
  yum:
    name: "{{ item }}"
  loop:
    - git

- name: Stopped and disable firewalld, if firewalld installed
  service:
    name: firewalld
    state: stopped
    enabled: no
