---

- name: Install virt-*
  yum:
    name: "{{ item }}"
  loop:
    - virt-install
    - virt-manager
    - cloud-utils
    - virt-viewer

- name: Enable & start service
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - libvirtd

- name: ensure direcroty exists
  file:
    path: "{{ cloudlab_image_dir }}"
    state: "directory"
    mode: "0555"

- name: Check image exists
  stat:
    path: "{{ cloudlab_image_dir }}/{{ centos_local_file }}"
  register: stat_result

- name: Download images
  get_url:
    url: "{{ centos_remote_url }}"
    dest: "{{ cloudlab_image_dir }}/{{ centos_local_file }}"
  when: not stat_result.stat.exists

- name: Copy cloudinit to target
  template:
    src: "cloudinit.j2"
    dest: "{{ cloudinit_txt }}"

- name: Check cloudinit_image exists
  stat:
    path: "{{ cloudinit_img }}"
  register: stat_result

- name: cloud-localds
  shell: "cloud-localds {{ cloudinit_img }} {{cloudinit_txt}}"
  when: not stat_result.stat.exists

- name: ensure vm volume dir exists
  file:
    path: "{{ cloudlab_volume_dir }}"
    state: "directory"
    mode: "0555"

- name: Parepare disk
  shell: "[ ! -f {{ cloudlab_volume_dir }}/{{ item.name }}.qcow2 ] && qemu-img convert -O qcow2 {{ cloudlab_image_dir }}/{{ centos_local_file }} {{ cloudlab_volume_dir }}/{{ item.name }}.qcow2 || echo 0"
  loop: "{{ vms }}"

- name: Create VM cmd
  debug:
    msg: "virt-install --name={{ item.name }} --ram={{ item.ram }} --vcpus={{ item.cpu }} --import --disk path={{ cloudlab_volume_dir }}/{{ item.name }}.qcow2,format=qcow2 --disk path={{ cloudlab_image_dir }}/cloudinit.img,device=cdrom --os-variant=centos7.0 --network bridge=virbr0,model=virtio --check path_in_use=off --noautoconsole"
  loop: "{{ vms }}"

# https://sumit-ghosh.com/articles/create-vm-using-libvirt-cloud-images-cloud-init/
# - name: Create VM
#   shell: "virt-install --name={{ item.name }} --ram={{ item.ram }} --vcpus={{ item.cpu }} --import --disk path=/root/cloudlab/volumes/{{ item.name }}.qcow2,format=qcow2 --disk path=/root/cloudlab/images/cloudinit.img,device=cdrom --os-variant=centos7.0 --network default,model=virtio --check path_in_use=off --noautoconsole"
