---

- name: Install virt-*
  yum:
    name: "{{ item }}"
  loop:
    - virt-install
    - virt-manager
    - cloud-utils
    - virt-viewer

- name: Enable & start service
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - libvirtd

- name: ensure direcroty exists
  file:
    path: "{{ cloudlab_image_dir }}"
    state: "directory"
    mode: "0555"

- name: Check image exists
  stat:
    path: "{{ cloudlab_image_dir }}/{{ centos_local_file }}"
  register: stat_result

- name: Download images
  get_url:
    url: "{{ centos_remote_url }}"
    dest: "{{ cloudlab_image_dir }}/{{ centos_local_file }}"
  when: not stat_result.stat.exists

- name: Copy cloudinit to target
  template:
    src: "cloudinit.j2"
    dest: "{{ cloudlab_image_dir }}/cloudinit-{{ item }}.txt"
  loop: "{{ groups['vms'] }}"

- name: cloud-localds
  shell: "rm -rf {{ cloudlab_image_dir }}/cloudinit-{{ item }}.img && cloud-localds {{ cloudlab_image_dir }}/cloudinit-{{ item }}.img {{ cloudlab_image_dir }}/cloudinit-{{ item }}.txt"
  loop: "{{ groups['vms'] }}"

- name: ensure vm volume dir exists
  file:
    path: "{{ cloudlab_volume_dir }}"
    state: "directory"
    mode: "0555"

- name: Parepare disk
  shell: "[ ! -f {{ cloudlab_volume_dir }}/{{ item }}.qcow2 ] && qemu-img convert -O qcow2 {{ cloudlab_image_dir }}/{{ centos_local_file }} {{ cloudlab_volume_dir }}/{{ item }}.qcow2 || echo 0"
  loop: "{{ groups['vms'] }}"

- name: Create VM cmd
  debug:
    msg: "virt-install --name={{ item }} --ram={{ hostvars[item]['ram'] }} --vcpus={{ hostvars[item]['cpu'] }} --import --disk path={{ cloudlab_volume_dir }}/{{ item }}.qcow2,format=qcow2 --disk path={{ cloudlab_image_dir }}/cloudinit-{{ item }}.img,device=cdrom --os-variant=centos7.0 --network bridge=virbr0,model=virtio --check path_in_use=off --noautoconsole"
  loop: "{{ groups['vms'] }}"

# https://sumit-ghosh.com/articles/create-vm-using-libvirt-cloud-images-cloud-init/
# virsh list | grep node | awk '{print $2}' | xargs -I{} virsh shutdown {}
# virsh list --all | grep node | awk '{print $2}' | xargs -I{} virsh undefine --domain {} --remove-all-storage
- name: Create VM
  shell: "virt-install --name={{ item }} --ram={{ hostvars[item]['ram'] }} --vcpus={{ hostvars[item]['cpu'] }} --import --disk path={{ cloudlab_volume_dir }}/{{ item }}.qcow2,format=qcow2 --disk path={{ cloudlab_image_dir }}/cloudinit-{{ item }}.img,device=cdrom --os-variant=centos7.0 --network bridge=virbr0,model=virtio --check path_in_use=off --noautoconsole"
  loop: "{{ groups['vms'] }}"
