- name: "Format {{ vmdisk_device }} to {{ vmdisk_fstype }}"
  filesystem:
    fstype: "{{ vmdisk_fstype }}"
    dev: "{{ vmdisk_device }}"
  when: use_vmdisk_device | bool

- name: "Mkdir {{ vmdisk_path }}"
  file:
    path: "{{ vmdisk_path }}"
    state: "directory" 
    mode: "0755"
  when: use_vmdisk_device | bool

- name: "Mount {{ vmdisk_device }} present"
  mount:
    path: "{{ vmdisk_path }}"
    src: "{{ vmdisk_device }}"
    state: "present"
    fstype: "{{ vmdisk_fstype }}"
    opts: "gquota"
  when: use_vmdisk_device | bool

- name: restorecon {{ vmdisk_path }}
  shell: "restorecon -R {{ vmdisk_path }}"
  when: use_vmdisk_device | bool

- name: "Mount {{ vmdisk_device }} mounted"
  mount:
    path: "{{ vmdisk_path }}"
    src: "{{ vmdisk_device }}"
    state: "mounted"
    fstype: "{{ vmdisk_fstype }}"
    opts: "gquota"
  when: use_vmdisk_device | bool
