- hosts: cloudlabs
  roles:
    - init01-prepare
    - init02-rdp
    - init03-01-kvm
    - init03-02-createvm
  become: yes

- hosts: vms
  roles:
    - init00-base
    - init01-prepare
    # - init02-rdp
    # - init03-createvm
    # - init04-prek8s
  become: yes

- hosts: cloudlabs
  roles:
    - init06-snapshot
  vars:
    snapshot_postfix: "init"
  become: yes