---

- name: Install epel release
  yum:
    name: epel-release

- name: Yum update all
  yum:
    name: '*'
    state: latest
    exclude: kernel*

- name: "Config sshd"
  lineinfile:
    path: "/etc/ssh/sshd_config"
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - {regexp: '^\s*ClientAliveInterval\s+', line: 'ClientAliveInterval 120'}
    - {regexp: '^\s*ClientAliveCountMax\s+', line: 'ClientAliveCountMax 720'}
    - {regexp: '^\s*GSSAPIAuthentication\s+', line: 'GSSAPIAuthentication no'}
    - {regexp: '^\s*UseDNS\s+', line: 'UseDNS no'}

- name: "Restart sshd"
  systemd:
    state: restarted
    daemon_reload: yes
    name: sshd

- name: change user passwd
  user: name={{ item.name }} password={{ item.chpass | password_hash('sha512', 'mysecretsalt') }}
  with_items:
       - { name: 'root', chpass: '{{ rootpass }}' }

- name: Install common packages
  yum:
    name: "{{ item }}"
  loop:
    - git

# yum group list hidden ids | grep -i GNOME
- name: Install the 'GNOME Desktop' group
  yum:
    name: "@^gnome-desktop-environment"
    state: present

- name: Install xrdp
  yum:
    name: xrdp
    enablerepo: "epel"

- name: Enable service
  service:
    name: "{{ item }}"
    enabled: yes
  loop:
    - xrdp

- name: Start service
  service:
    name: "{{ item }}"
    state: started
  loop:
    - xrdp
