---

- name: Check cpu acceleration
  shell: "grep -qE '(vmx|svm)' /proc/cpuinfo;echo $?"
  register: cpu_acceleration
  when: check_vt | bool

- name: Fail if acc is not enabled and supported
  fail:
    msg: "acc is not enabled and supported"
  when: check_vt | bool and cpu_acceleration.stdout != "0"

- name: Install virt-*
  yum:
    name: "{{ item }}"
  loop:
    - virt-install
    - virt-manager
    - cloud-utils
    - virt-viewer
    - bridge-utils
    # - iptables-services
    # - NetworkManager

- name: Enable & start service
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - libvirtd
    # - iptables

- name: Enable ip forward function
  shell: "echo 1 > /proc/sys/net/ipv4/ip_forward"

- name: "cmd: ip link show type bridge"
  shell: "ip link show type bridge"
  register: check_result

- name: "Dump check_result.stdout_lines"
  debug:
    msg: "{{ check_result.stdout_lines }}"

# - name: Add linux bridge
#   command: "ip link add {{ item }} type bridge"
#   when: "item not in check_result.stdout"
#   loop:
#     - "br-mgt"
#     - "br-pod"
#     - "br-ext"
#     - "br-str"

# - name: Install bridge configure file
#   template:
#     src: "{{ item }}"
#     dest: /etc/sysconfig/network-scripts/{{ item }}
#   loop:
#     - ifcfg-br-ext
#     - ifcfg-br-mgt
#     - ifcfg-br-pod
#     - ifcfg-br-str

# - name: Restart NetworkManager
#   service:
#     name: NetworkManager
#     state: restarted

# - name: Create config file for linux bridge
#   shell: "ifup {{ item }}"
#   loop:
#     - br-ext
#     - br-mgt
#     - br-pod
#     - br-str

# https://www.linuxtechi.com/enable-nested-virtualization-kvm-centos-7-rhel-7/
- name: Touch /etc/modprobe.d/kvm-nested.conf
  copy:
    src: "kvm-nested.conf"
    dest: "/etc/modprobe.d/kvm-nested.conf"
  when: check_vt | bool

- name: Enable KVM nested
  shell: "modprobe -r kvm_intel && modprobe -a kvm_intel"
  ignore_errors: yes
  when: check_vt | bool
